// Receituários com parâmetros informados pelo profissional a partir de seu protocolo.
(() => {
  const field=(name,label,type='text',attrs='')=>`<div class="form-group"><label for="${name}">${label}</label><input class="form-control" id="${name}" name="${name}" type="${type}" ${attrs}></div>`;
  const area=(name,label,attrs='')=>`<div class="form-group"><label for="${name}">${label}</label><textarea class="form-control" id="${name}" name="${name}" ${attrs}></textarea></div>`;
  const select=(name,label,values)=>`<div class="form-group"><label for="${name}">${label}</label><select class="form-control" id="${name}" name="${name}">${values.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></div>`;
  const panel=(title,content)=>`<section class="module-panel"><h2>${title}</h2>${content}</section>`;
  const dadosPaciente=field('rxPaciente','Nome completo do paciente','text','required maxlength="160"')+field('rxNascimento','Data de nascimento','date','required')+select('rxSexo','Sexo',[['','Selecione…'],['Feminino','Feminino'],['Masculino','Masculino'],['Não informado','Não informado']])+field('rxPeso','Peso (kg)','number','min="0.1" max="300" step="0.01"')+field('rxAltura','Altura (cm)','number','min="10" max="250" step="0.1"')+field('rxEnderecoPaciente','Endereço completo do paciente','text','required maxlength="300"');
  const prescritor=field('rxNome','Nome do enfermeiro','text','required maxlength="160"')+field('rxCoren','COREN-ENF','text','required maxlength="30"')+field('rxUf','UF','text','required minlength="2" maxlength="2" pattern="[A-Za-z]{2}"')+field('rxEspecialidade','Especialização (se houver)')+field('rxCpf','CPF do prescritor','text','required maxlength="14"')+field('rxTelefone','Telefone','tel','required maxlength="25"')+field('rxEmail','E-mail','email')+field('rxServico','Serviço de saúde','text','required maxlength="160"')+field('rxCnpj','CNPJ','text','required maxlength="18"')+field('rxEndereco','Endereço profissional','text','required maxlength="300"')+field('rxCidade','Cidade','text','required maxlength="100"')+field('rxData','Data de emissão','date','required');
  const protocolo=field('rxProtocolo','Protocolo utilizado','text','required maxlength="250"')+field('rxAno','Ano de publicação/aprovação','number','required min="1900" max="2100"')+field('rxInstituicao','Instituição/órgão que aprovou o protocolo','text','required maxlength="250"');
  const meds=[['Sais de reidratação oral','Hidratação'],['Nistatina','Antifúngico'],['Cefalexina','Antibiótico'],['Mupirocina','Antibiótico tópico'],['Neomicina + bacitracina','Antibiótico tópico'],['Amoxicilina','Antibiótico'],['Amoxicilina + clavulanato','Antibiótico'],['Eritromicina','Antibiótico'],['Penicilina benzatina','Antibiótico injetável'],['Ceftriaxona','Antibiótico injetável'],['Sulfametoxazol + trimetoprim','Antibiótico'],['Azitromicina','Antibiótico'],['Paracetamol','Antitérmico/Analgésico'],['Dipirona','Antitérmico/Analgésico'],['Ibuprofeno','Antitérmico/Anti-inflamatório'],['Mebendazol','Antiparasitário'],['Albendazol','Antiparasitário'],['Sulfato ferroso','Suplemento'],['Vitamina A','Suplemento'],['Ondansetrona','Antiemético']];
  const catalogo=select('rxCategoria','Filtrar categoria',[['','Todas as categorias'],...[...new Set(meds.map(m=>m[1]))].map(c=>[c,c])])+`<div class="video-grid" id="catalogoMedicamentos">${meds.map(([nome,categoria],i)=>`<button type="button" class="document-card" data-med="${i}" data-categoria="${categoria}"><h3>${nome}</h3><p>${categoria}</p><span>Selecionar para preencher posologia</span></button>`).join('')}</div>`;
  const medicamento=field('rxMedicamento','Medicamento — denominação genérica','text','maxlength="160"')+field('rxApresentacao','Apresentação e concentração do produto','text','maxlength="200"')+field('rxVia','Via de administração','text','maxlength="100"')+field('rxDose','Dose por tomada (texto final)','text','maxlength="200"')+field('rxFrequencia','Frequência/intervalo','text','maxlength="120"')+field('rxDuracao','Duração','text','maxlength="120"')+field('rxQuantidade','Quantidade a dispensar','text','maxlength="120"');
  const calculadora=select('calcTipo','Unidade da dose do protocolo',[['mg/kg/dose','mg/kg por dose'],['mg/kg/dia','mg/kg por dia'],['mg/dose','mg por dose']])+field('calcDose','Dose do protocolo','number','min="0.001" step="any"')+field('calcConcentracao','Concentração do princípio ativo (mg/mL)','number','min="0.001" step="any"')+field('calcTomadas','Tomadas por dia','number','min="1" max="24" step="1"')+field('calcMaxDose','Máximo por dose (mg), se definido','number','min="0.001" step="any"')+field('calcMaxDia','Máximo diário (mg), se definido','number','min="0.001" step="any"');
  document.querySelector('.main-content').insertAdjacentHTML('beforeend',`<section id="view-receituario" class="page-view inner-view"><button class="btn-voltar open-view" data-target="view-dashboard">← Voltar ao Início</button><header class="module-header-text"><h1 tabindex="-1">Receituários e cálculo de dose</h1><p>Preenchimento profissional conforme o protocolo do serviço de saúde.</p></header><div class="notice">Informe o protocolo e confira indicação, dose, apresentação e via antes de emitir. O cálculo abaixo apenas converte os parâmetros informados; não seleciona tratamentos.</div><form id="formReceituario">${panel('Dados do paciente',`<div class="form-grid">${dadosPaciente}</div><output id="rxIdade" aria-live="polite"></output>`)}${panel('Dados do prescritor',`<div class="form-grid">${prescritor}</div>`)}${panel('Respaldo da prescrição',`<div class="form-grid">${protocolo}</div><p class="source-note">Referência: <a href="https://www.cofen.gov.br/resolucao-cofen-no-801-de-14-de-janeiro-de-2026/" target="_blank" rel="noopener noreferrer">Resolução COFEN 801/2026</a>.</p>`)}${panel('Medicamentos citados no material do projeto',catalogo)}${panel('Adicionar medicamento',`<div class="form-grid">${medicamento}</div><label class="check-item"><input type="checkbox" id="rxRetencao"><span>Medicamento sujeito à retenção da receita</span></label><details><summary>Calculadora de conversão de dose em mg e mL</summary><p class="storage-note">Use a concentração do princípio ativo correspondente à dose. Associações exigem identificar o componente usado no cálculo. Não converte gotas, UI ou apresentações sólidas.</p><div class="form-grid">${calculadora}</div><button class="btn btn-cancel" type="button" id="calcularDose">Calcular</button><output id="calcResultado" class="notice" aria-live="polite">Preencha os parâmetros do protocolo.</output><button class="btn btn-cancel" type="button" id="usarDose" disabled>Usar resultado na dose por tomada</button></details><button type="button" class="btn btn-primary" id="adicionarMedicamento">+ Adicionar à prescrição</button>`)}${panel('Prescrições selecionadas','<div id="rxLista"><p>Nenhum medicamento adicionado.</p></div>'+area('rxTexto','Texto final da prescrição — revise antes de imprimir','required maxlength="16000"'))}<div class="form-actions"><button type="submit" class="btn btn-primary" name="tipo" value="simples">Receituário simples</button><button type="submit" class="btn btn-primary" name="tipo" value="retencao">Receituário de antibióticos / retenção</button><button type="button" class="btn btn-cancel" id="rxLimpar">Limpar receituário</button></div><p class="storage-note">A impressão abre o diálogo do navegador. O receituário para retenção contém duas vias e campos de comprador/fornecedor para preenchimento na dispensação. A assinatura deve ser realizada pelo profissional.</p></form></section>`);
  let itens=[],resultado=null,doseCalculada=null;
  const el=id=>document.getElementById(id);
  const limparResultado=()=>{if(doseCalculada!==null&&el('rxDose').value===doseCalculada)el('rxDose').value='';doseCalculada=null;resultado=null;el('usarDose').disabled=true;el('calcResultado').textContent='Preencha os parâmetros e calcule novamente.';};
  el('rxCategoria').addEventListener('change',()=>document.querySelectorAll('[data-med]').forEach(b=>b.hidden=!!el('rxCategoria').value&&b.dataset.categoria!==el('rxCategoria').value));
  document.querySelectorAll('[data-med]').forEach(b=>b.addEventListener('click',()=>{
    el('rxMedicamento').value=meds[Number(b.dataset.med)][0];el('rxRetencao').checked=meds[Number(b.dataset.med)][1].startsWith('Antibiótico');
    ['rxApresentacao','rxVia','rxDose','rxFrequencia','rxDuracao','rxQuantidade','calcDose','calcConcentracao','calcTomadas','calcMaxDose','calcMaxDia'].forEach(id=>el(id).value='');limparResultado();el('rxApresentacao').focus();
  }));
  ['rxPeso','calcTipo','calcDose','calcConcentracao','calcTomadas','calcMaxDose','calcMaxDia'].forEach(id=>el(id).addEventListener('input',limparResultado));
  el('rxNascimento').addEventListener('change',()=>{const meses=idadeMeses(el('rxNascimento').value);el('rxNascimento').setCustomValidity(meses===null?'Informe uma data de nascimento válida.':'');el('rxIdade').textContent=meses===null?'':`${Math.floor(meses/12)} ano(s) e ${meses%12} mês(es).`;});
  el('calcularDose').addEventListener('click',()=>{
    limparResultado();try{resultado=calcularConversao({tipo:el('calcTipo').value,peso:Number(el('rxPeso').value),dose:Number(el('calcDose').value),concentracao:Number(el('calcConcentracao').value),tomadas:Number(el('calcTomadas').value),maxDose:el('calcMaxDose').value?Number(el('calcMaxDose').value):null,maxDia:el('calcMaxDia').value?Number(el('calcMaxDia').value):null});
      el('calcResultado').textContent=`${resultado.mg.toLocaleString('pt-BR',{maximumFractionDigits:4})} mg por tomada = ${resultado.ml.toLocaleString('pt-BR',{maximumFractionDigits:4})} mL por tomada; ${resultado.dia.toLocaleString('pt-BR',{maximumFractionDigits:4})} mg/dia. Confira o arredondamento e o dispositivo de medida.`;el('usarDose').disabled=false;
    }catch(error){el('calcResultado').textContent=error.message;}
  });
  el('usarDose').addEventListener('click',()=>{if(resultado){doseCalculada=`${resultado.mg.toLocaleString('pt-BR',{maximumFractionDigits:4})} mg (${resultado.ml.toLocaleString('pt-BR',{maximumFractionDigits:4})} mL) por tomada`;el('rxDose').value=doseCalculada;}});
  function renderItens(){
    el('rxLista').innerHTML=itens.map((m,i)=>`<div class="child-row"><p>${escapeHTML(m.nome)} · ${escapeHTML(m.dose)}${m.retencao?' · Retenção':''}</p><button type="button" class="btn btn-cancel" data-remover-med="${i}">Remover</button></div>`).join('')||'<p>Nenhum medicamento adicionado.</p>';
    el('rxTexto').value=itens.map((m,i)=>`${i+1}. ${m.nome} — ${m.apresentacao}\nVia: ${m.via}. Dose: ${m.dose}.\nFrequência: ${m.frequencia}. Duração: ${m.duracao}.\nQuantidade: ${m.quantidade}.`).join('\n\n');
  }
  el('adicionarMedicamento').addEventListener('click',()=>{
    const campos={nome:'rxMedicamento',apresentacao:'rxApresentacao',via:'rxVia',dose:'rxDose',frequencia:'rxFrequencia',duracao:'rxDuracao',quantidade:'rxQuantidade'};const item={};
    for(const [key,id]of Object.entries(campos)){item[key]=el(id).value.trim();if(!item[key]){mostrarAviso('Preencha todos os dados do medicamento.','error');el(id).focus();return;}}
    item.retencao=el('rxRetencao').checked;item.peso=el('rxPeso').value;item.nascimento=el('rxNascimento').value;itens.push(item);renderItens();mostrarAviso('Medicamento adicionado. Revise o texto final.');
  });
  el('rxLista').addEventListener('click',event=>{const b=event.target.closest('[data-remover-med]');if(b){itens.splice(Number(b.dataset.removerMed),1);renderItens();}});
  el('rxLimpar').addEventListener('click',()=>{if(!confirm('Limpar os dados e medicamentos deste receituário?'))return;el('formReceituario').reset();itens=[];renderItens();limparResultado();el('rxIdade').textContent='';el('rxData').value=dataHoje();});
  el('formReceituario').addEventListener('submit',event=>{
    event.preventDefault();if(!exigirAcesso('view-receituario'))return;const tipo=event.submitter?.value||'simples';if(!event.currentTarget.reportValidity())return;
    if(!itens.length){mostrarAviso('Adicione pelo menos um medicamento.','error');return;}
    if(itens.some(m=>m.peso!==el('rxPeso').value||m.nascimento!==el('rxNascimento').value)){mostrarAviso('Peso ou nascimento alterado após adicionar medicamentos. Remova e adicione novamente os itens após revisar as doses.','error');return;}
    if(tipo==='simples'&&itens.some(m=>m.retencao)){mostrarAviso('Há medicamento sujeito à retenção. Use o receituário de retenção.','error');return;}
    if(idadeMeses(el('rxNascimento').value,el('rxData').value)===null){mostrarAviso('A emissão não pode ser anterior ao nascimento.','error');return;}
    const texto=el('rxTexto').value.trim();if(!texto){mostrarAviso('Revise o texto da prescrição.','error');return;}
    const v=id=>escapeHTML(el(id).value.trim());
    const via=(numero)=>`<article class="print-page"><h1>${tipo==='simples'?'RECEITUÁRIO SIMPLES':'RECEITUÁRIO SUJEITO À RETENÇÃO'}</h1>${tipo==='retencao'?`<p><strong>${numero===1?'1ª VIA — PACIENTE':'2ª VIA — FARMÁCIA'}</strong></p>`:''}<div class="rx-box rx-grid"><div><p><strong>IDENTIFICAÇÃO DO PRESCRITOR</strong></p><p>Nome: ${v('rxNome')}</p><p>COREN-ENF: ${v('rxCoren')} · UF: ${v('rxUf')}</p><p>Especialização: ${v('rxEspecialidade')||'—'}</p><p>CPF: ${v('rxCpf')}</p><p>Endereço: ${v('rxEndereco')}</p><p>Cidade: ${v('rxCidade')} · ${v('rxUf')}</p><p>Telefone: ${v('rxTelefone')}</p><p>E-mail: ${v('rxEmail')||'—'}</p></div><div><p><strong>SERVIÇO DE SAÚDE</strong></p><p>${v('rxServico')}</p><p>CNPJ: ${v('rxCnpj')}</p><p>Data: ${v('rxData')}</p></div></div><div class="rx-box"><p><strong>PACIENTE:</strong> ${v('rxPaciente')}</p><p>Nascimento: ${v('rxNascimento')} · Sexo: ${v('rxSexo')||'Não informado'}</p><p>Endereço: ${v('rxEnderecoPaciente')}</p><p>Peso: ${v('rxPeso')||'—'} kg · Altura: ${v('rxAltura')||'—'} cm</p></div><div class="rx-box"><h2>PRESCRIÇÃO</h2><div class="rx-body">${escapeHTML(texto)}</div></div><div class="rx-box"><p>Protocolo: ${v('rxProtocolo')} · Ano: ${v('rxAno')}</p><p>Instituição/órgão que aprovou: ${v('rxInstituicao')}</p></div><div class="signature">________________________________________________<br>Assinatura do(a) enfermeiro(a)<br>${v('rxNome')} · COREN-${v('rxUf')} ${v('rxCoren')}-ENF</div>${tipo==='retencao'?'<div class="rx-grid"><div class="rx-box"><p><strong>IDENTIFICAÇÃO DO COMPRADOR</strong></p><p>Nome: __________________________________</p><p>RG/órgão expedidor: ________________________</p><p>CPF: ___________________________________</p><p>Endereço: ________________________________</p><p>Cidade/UF: _______________________________</p><p>Telefone: ________________________________</p></div><div class="rx-box"><p><strong>IDENTIFICAÇÃO DO FORNECEDOR</strong></p><p>Farmacêutico/CRF/UF: _______________________</p><p>Farmácia/CNPJ: ____________________________</p><p>Endereço: ________________________________</p><p>Telefone: ________________________________</p><p>Assinatura: _______________________________</p><p>Data da dispensação: _______________________</p></div></div>':''}</article>`;
    imprimirHTML(via(1)+(tipo==='retencao'?via(2):''));
  });
  window.addEventListener('conta-alterada',()=>{el('formReceituario').reset();itens=[];renderItens();limparResultado();el('rxNascimento').setCustomValidity('');el('rxIdade').textContent='';el('rxData').value=dataHoje();});
  window.addEventListener('DOMContentLoaded',()=>el('rxData').value=dataHoje());
})();

