// Montagem dos módulos adicionais antes de registrar a navegação.
(() => {
  const dados = window.PUERICULTURA_CONTEUDO;
  const esc = text => String(text).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lista = items => `<ul class="module-list check">${items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`;
  const card = (title, content) => `<section class="module-card"><h3>${esc(title)}</h3>${content}</section>`;
  const field = (name, label, type='text', attrs='') => `<div class="form-group"><label for="${name}">${label}</label><input class="form-control" id="${name}" name="${name}" type="${type}" ${attrs}></div>`;
  const area = (name,label,attrs='') => `<div class="form-group"><label for="${name}">${label}</label><textarea class="form-control" id="${name}" name="${name}" ${attrs}></textarea></div>`;
  const options = (name,label,values,attrs='') => `<div class="form-group"><label for="${name}">${label}</label><select class="form-control" name="${name}" id="${name}" ${attrs}><option value="">Selecione…</option>${values.map(v=>`<option>${esc(v)}</option>`).join('')}</select></div>`;
  const checks = (name,items) => `<div class="check-grid">${items.map((t,i)=>`<label class="check-item"><input type="checkbox" name="${name}" value="${esc(t)}"><span>${esc(t)}</span></label>`).join('')}</div>`;
  const back = '<button class="btn-voltar open-view" data-target="view-dashboard">← Voltar ao Início</button>';
  const view = (id,title,subtitle,content) => `<section id="${id}" class="page-view inner-view">${back}<header class="module-header-text"><h1 tabindex="-1">${title}</h1><p>${subtitle}</p></header>${content}</section>`;
  const main = document.querySelector('.main-content');
  document.querySelectorAll('[data-target="view-amamentacao"] h3').forEach(el=>el.textContent='Guia de Amamentação');
  document.querySelectorAll('img[alt="Apoio à Amamentação"]').forEach(el=>el.alt='Guia de Amamentação');
  const nav = document.querySelector('.nav-menu');
  nav.insertAdjacentHTML('beforeend', '<li><a href="#view-nova-consulta" class="nav-link" data-target="view-nova-consulta"><span aria-hidden="true">♧</span>Nova Consulta</a></li><li><a href="#view-caderneta" class="nav-link" data-target="view-caderneta"><span aria-hidden="true">▤</span>Caderneta da Criança</a></li><li><a href="#view-educador" class="nav-link" data-target="view-educador"><span aria-hidden="true">▤</span>Formulário do Educador</a></li><li><a href="#view-noticias" class="nav-link" data-target="view-noticias"><span aria-hidden="true">▧</span>Notícias</a></li>');
  const consultas = document.querySelector('#view-consultas .module-wrapper');
  consultas.innerHTML = `<header class="module-header-text"><h1 tabindex="-1">Consultas de Rotina</h1><p>Acompanhamento preventivo do crescimento e desenvolvimento infantil.</p></header><div class="notice">Prevenção é cuidado: leve a Caderneta da Criança, cartão de vacinas, exames e informações sobre medicamentos em uso.</div><section class="module-panel"><h2>Cronograma de consultas</h2><p>Selecione o período para ver o roteiro de avaliação.</p><div class="timeline-grid">${dados.consultas.map(([label],i)=>`<button class="timeline-btn" data-periodo="${i}" aria-pressed="false">${label}</button>`).join('')}</div><p class="storage-note">A partir dos 2 anos, acompanhamento no mínimo anual. A frequência pode ser ampliada conforme a necessidade da criança.</p></section><section id="detalheConsulta" aria-live="polite" class="module-panel"><p>Selecione uma faixa etária acima.</p></section><div class="tool-grid">${card('Avaliação física',lista(['Antropometria e trajetória de crescimento','Exame físico, sinais vitais e avaliação nutricional']))}${card('Desenvolvimento',lista(['Habilidades motoras e comunicação','Interação, brincadeira e relatos da família']))}${card('Orientações',lista(['Alimentação, higiene e sono','Estímulos, vacinação e prevenção de acidentes']))}</div><p class="source-note">Fonte: <a href="https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-crianca/primeira-infancia" target="_blank" rel="noopener noreferrer">Ministério da Saúde — Primeira Infância</a>. Roteiros de apoio adaptados do material do projeto.</p>`;
  document.querySelector('#view-amamentacao .module-wrapper').innerHTML = `<header class="module-header-text"><h1 tabindex="-1">Guia de Amamentação</h1><p>Acolhimento, informação e apoio ao aleitamento materno.</p></header><div class="notice success">Aleitamento materno exclusivo até os 6 meses, com alimentação complementar a partir dessa idade, mantendo a amamentação até 2 anos ou mais.</div><div class="tool-grid">${card('Para o bebê','<p>Alimentação, proteção contra infecções e fortalecimento do vínculo com a mãe.</p>')}${card('Para a mãe','<p>Apoia a recuperação pós-parto e está associado à redução do risco de câncer de mama e de ovário.</p>')}${card('Para a sociedade','<p>Contribui para reduzir custos em saúde e o impacto ambiental da alimentação.</p>')}</div><div class="module-grid">${card('Posição e pega',lista(['Mãe confortável, bebê próximo e voltado para ela.','Cabeça e corpo alinhados, com apoio ao corpo do bebê.','Boca bem aberta, lábios voltados para fora e queixo junto à mama.','Mais aréola visível acima da boca; nariz livre.']))}${card('Dificuldades comuns',lista(['Dor, fissuras ou dificuldade para mamar: observar a mamada com um profissional.','A percepção de pouco leite precisa ser avaliada junto às mamadas e ao crescimento.','Manter oferta em livre demanda; buscar apoio na UBS ou banco de leite.','Febre, mama muito dolorosa/vermelha ou bebê prostrado exigem avaliação.']))}</div>${card('Acompanhando a amamentação',lista(['Observar sucção e deglutição, conforto e interação.','Acompanhar ganho de peso e fraldas molhadas conforme a idade.','Mudanças no peito ou duração da mamada, isoladamente, não medem a produção de leite.']))}<p class="source-note">Referência: <a target="_blank" rel="noopener noreferrer" href="https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/a/aleitamento-materno">Ministério da Saúde — Amamentação</a>.</p><section class="module-panel"><h2>Vídeos e materiais didáticos</h2><p>Seleção indicada pela equipe do projeto. Abra cada vídeo para assistir na fonte.</p><div class="video-grid">${window.VIDEOS_AMAMENTACAO.map(v=>`<a class="video-card" href="${esc(v.url)}" target="_blank" rel="noopener noreferrer"><span class="video-thumb"><img loading="lazy" src="https://i.ytimg.com/vi/${esc(v.id)}/hqdefault.jpg" alt=""><span aria-hidden="true" class="play-symbol">▶</span></span><h3>${esc(v.title)}</h3><span>Assistir no YouTube ↗</span></a>`).join('')}<a class="video-card" href="https://www.facebook.com/watch/?v=425166329578708" target="_blank" rel="noopener noreferrer"><span class="video-thumb video-thumb-facebook"><span aria-hidden="true" class="play-symbol">▶</span></span><h3>Amamentação: uma coisa incrível</h3><span>Assistir no Facebook ↗</span></a></div></section>`;
  document.querySelector('#view-educacao .module-wrapper').innerHTML = `<header class="module-header-text"><h1 tabindex="-1">Educação Familiar</h1><p>Apoio a pais e cuidadores para o desenvolvimento saudável das crianças.</p></header><div class="notice">A família é um ambiente fundamental de aprendizagem, vínculo e proteção. O cuidado se constrói com escuta e apoio.</div><div class="module-grid">${card('Cuidados domiciliares',lista(['Higiene e banho do bebê','Cuidados com o umbigo','Reconhecimento de sinais de alerta','Ambiente seguro e prevenção de acidentes']))}${card('Desenvolvimento infantil',lista(['Brincadeiras e estímulos adequados à idade','Leitura e conversa desde cedo','Acompanhamento dos marcos do desenvolvimento','Limites e disciplina positiva']))}${card('Dinâmica familiar',lista(['Adaptação à chegada do bebê','Divisão de tarefas e cuidado com irmãos','Rede de apoio e saúde mental dos cuidadores']))}${card('Comunicação',lista(['Conversar com a criança e praticar escuta ativa','Nomear sentimentos e acolher necessidades','Resolver conflitos e fortalecer vínculos']))}${card('Estratégias educativas',lista(['Demonstrações durante consultas e visitas','Materiais ilustrados e grupos de apoio','Orientações individualizadas e encorajamento']))}${card('Temas por idade',lista(['0–6 meses: aleitamento, vínculo e cuidados básicos','6–12 meses: alimentação complementar e segurança','1–2 anos: desenvolvimento motor e rotinas','2 anos ou mais: socialização e autonomia']))}</div>`;

  const ident = field('edNome','Nome do bebê/criança','text','required maxlength="160"')+field('edNascimento','Data de nascimento','date','required')+options('edTurma','Turma',Object.keys(dados.educador),'required')+field('edResponsavel','Educador responsável','text','required maxlength="160"')+field('edData','Data do preenchimento','date','required')+field('edEscola','Escola/creche','text','required maxlength="160"')+field('edCoordenacaoEmail','E-mail da coordenação','email','required maxlength="254" autocomplete="email"');
  const edForm = `<form id="formEducador"><input type="hidden" name="edId" id="edId">${card('1. Identificação',`<div class="form-grid">${ident}</div><output id="edIdade" aria-live="polite"></output>`)}${card('2. Carteira de saúde e acompanhamento',options('edVacinacao','A carteira de vacinação está atualizada?',['Sim','Não','Faltam vacinas para a idade','Não informado'],'required')+'<div id="edVacinaAlerta" class="notice warning" role="status" hidden>⚠ Vacinação pendente: o e-mail para a coordenação será identificado como alerta vacinal.</div>'+area('edVacinasFaltantes','Vacinas pendentes informadas')+options('edConsultas','Consultas de puericultura',['Em dia','Em atraso','Família relata dificuldade de agendamento','Não informado'],'required'))}${card('3. Indicadores do desenvolvimento','<p>Assinale somente o que foi observado, considerando a idade. O registro apoia o encaminhamento e não estabelece diagnóstico.</p>'+Object.entries(dados.educador).map(([t,items])=>`<fieldset><legend>${esc(t)}</legend>${checks('edDesenvolvimento',items)}</fieldset>`).join(''))}${card('4. Sinais gerais de alerta',checks('edSinais',dados.sinais))}${card('5. Observações do educador',area('edObservacoes','Descreva episódios, contexto e frequência das observações','maxlength="8000"'))}${card('6. Próximos passos',checks('edEncaminhamentos',dados.encaminhamentos))}<div class="form-actions"><button type="reset" class="btn btn-cancel">Novo formulário</button><button type="submit" class="btn btn-primary">Salvar e preparar e-mail</button></div><div id="edNotificacao" class="notice success" hidden><strong>Relatório salvo.</strong><p>Revise o destinatário e o conteúdo antes de enviar pelo seu aplicativo de e-mail.</p><a id="edEmailLink" class="btn btn-primary" href="#">Abrir e-mail para a coordenação</a></div><p class="storage-note">O relatório fica salvo na conta do educador. O botão abre uma mensagem pronta; o envio é confirmado no aplicativo de e-mail.</p></form>`;
  const estudo = `<div id="painelEstudo" hidden>${card('Estudo & Protocolo — proteção na primeira infância','<p>Educadores podem observar mudanças físicas e comportamentais e registrar os fatos para articulação com a rede de proteção. Sinais isolados não comprovam violência; a ausência deles também não exclui uma situação de risco.</p>')}<div class="module-grid">${card('Violência física',lista(['Lesões recorrentes ou explicações incompatíveis','Queimaduras, hematomas e marcas observadas']))}${card('Negligência',lista(['Necessidades de alimentação, higiene ou saúde não atendidas','Investigar também barreiras de acesso e vulnerabilidade social']))}${card('Violência psicológica',lista(['Medo intenso, retraimento ou mudanças persistentes de comportamento','Regressão e alterações de sono']))}${card('Violência sexual',lista(['Relato espontâneo ou sinais que demandem avaliação especializada','Acolher sem pressionar a criança a repetir o relato']))}</div>${card('Instrumento de observação',`<p>Registre presença, ausência ou informação desconhecida.</p><form id="formObservacao">${dados.observacao.map((t,i)=>options('obs'+i,t,['Sim','Não','Não observado'])).join('')}<output id="observacaoResumo" class="notice" aria-live="polite">Nenhuma observação preenchida.</output><div class="form-actions"><button type="button" id="imprimirObservacao" class="btn btn-cancel">Imprimir observações</button></div></form><p class="storage-note">Este roteiro do projeto não possui escala de risco validada. A quantidade de sinais não define urgência nem substitui avaliação profissional.</p>`)}${card('Fluxo de encaminhamento','<ol class="flow-list"><li>Observar e registrar fatos, data e contexto.</li><li>Comunicar a coordenação e seguir o fluxo de proteção da instituição.</li><li>Articular a avaliação com a UBS/ESF e a rede de proteção.</li><li>Em suspeita ou confirmação de violência, comunicar ao Conselho Tutelar conforme o ECA. Situações urgentes não devem aguardar o preenchimento do formulário.</li></ol><p>Referência: <a href="https://www.planalto.gov.br/ccivil_03/leis/l8069.htm" target="_blank" rel="noopener noreferrer">Estatuto da Criança e do Adolescente</a>.</p>')}</div>`;
  main.insertAdjacentHTML('beforeend',view('view-educador','Formulário do Educador','Acompanhamento da puericultura e desenvolvimento de 0 a 3 anos.',`<div class="caderneta-tabs"><button class="tab-btn active" data-aba="formulario" aria-pressed="true">▤ Formulário</button><button class="tab-btn" data-aba="estudo" aria-pressed="false">▣ Estudo & Protocolo</button></div><div id="painelFormulario">${edForm}<section class="module-panel educator-history"><h2>Relatórios salvos</h2><div id="listaRelatoriosEducador"><p>Nenhum relatório salvo.</p></div></section></div>${estudo}`));
  main.insertAdjacentHTML('beforeend',view('view-documentos','Documentos e Legislação da Enfermagem','Referências para estudo e consulta no site oficial.',`${card('Puericultura e Processo de Enfermagem','<p>Acompanhamento do crescimento e desenvolvimento da criança, com avaliação, diagnóstico de enfermagem, planejamento, implementação e evolução. A consulta de enfermagem é privativa do enfermeiro; técnicos e auxiliares participam do cuidado sob supervisão.</p>')}<div class="document-list">${dados.documentos.map(([t,d,u])=>`<a class="document-card" href="${u}" target="_blank" rel="noopener noreferrer"><h2>${t}</h2><p>${d}</p><span>Acessar fonte oficial ↗</span></a>`).join('')}</div>`));
  const noticias = [
    ['Pós-graduação promove ciclo de formação para enfermeiros e técnicos da rede municipal','pos-graduacao-promove-ciclo-de-formacao-para-enfermeiros-e-tecnicos-da-rede-municipal-de-saude','assets/modulos/consultas-rotina.jpg','Formação continuada para profissionais da rede municipal.'],
    ['Disciplina de Enfermagem promove visitas técnicas a serviços de saúde','disciplina-de-enfermagem-promove-visitas-tecnicas-a-servicos-de-saude','assets/modulos/educacao-familiar.jpg','Atividades aproximam acadêmicos de diferentes cenários de atuação.'],
    ['Acadêmicos de Enfermagem desenvolvem ações de vacinação em empresas','academicos-de-enfermagem-desenvolvem-acoes-de-vacinacao-em-empresas','assets/modulos/imunizacao.jpg','Campanha mobiliza pessoas em momentos do LACENP em parceria com o Grupo Felice.']
  ];
  main.insertAdjacentHTML('beforeend',view('view-noticias','Notícias e ações em saúde','Seleção de notícias da Universidade Franciscana indicada no projeto.',`<div class="news-grid">${noticias.map(([t,slug,img,resumo])=>`<a class="news-card" href="https://site.ufn.edu.br/pagina/${slug}" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="${img}" alt=""><div><span class="tag">UFN · Enfermagem</span><h2>${t}</h2><p>${resumo}</p><span>Ler notícia ↗</span></div></a>`).join('')}</div>`));

  const cadastro = `<form id="formCrianca"><input type="hidden" id="criancaId" name="criancaId"><div class="form-grid">${field('criancaNome','Nome completo da criança','text','required maxlength="160"')}${field('criancaNascimento','Data de nascimento','date','required')}${field('criancaResponsavel','Responsável pela criança','text','required maxlength="160"')}${field('criancaProfissional','Profissional responsável','text','maxlength="160"')}</div><div class="form-actions"><button type="reset" class="btn btn-cancel">Limpar</button><button type="submit" class="btn btn-primary">Salvar criança</button></div></form>`;
  document.querySelector('#view-caderneta .caderneta-tabs').outerHTML = `<div class="form-actions"><button class="btn btn-primary" id="novaCrianca">+ Novo registro</button><button class="btn btn-cancel" id="exportarRegistros">Exportar registros</button></div><div class="module-panel" id="cadastroCrianca" hidden><h2>Novo registro de criança</h2>${cadastro}</div>`;
  document.getElementById('listaCriancasCadastradas').insertAdjacentHTML('afterend','<section class="module-panel"><h2>Consultas e formulários salvos</h2><div id="listaAtendimentos"></div></section>');
  const formConsulta = document.getElementById('formNovaConsulta');
  const tipoProtocolo = formConsulta.querySelector('select:not(#selectCrianca)');
  tipoProtocolo.id = 'tipoProtocolo'; tipoProtocolo.name = 'protocolo';
  tipoProtocolo.previousElementSibling.setAttribute('for', 'tipoProtocolo');
  formConsulta.insertAdjacentHTML('afterbegin','<input type="hidden" name="consultaId" id="consultaId">');
  formConsulta.querySelector('.form-grid').insertAdjacentHTML('beforeend',field('nomeProfissional','Profissional responsável','text','required maxlength="160"'));
  const select = document.getElementById('selectCrianca'); select.name='crianca'; select.innerHTML='<option value="">Cadastre uma criança na Caderneta Digital</option>';
  document.getElementById('dataConsulta').name='data'; document.getElementById('dataConsulta').removeAttribute('value');
  formConsulta.querySelectorAll('textarea').forEach((el,i)=>{el.name=['queixa','exame','diagnostico','intervencoes','orientacoes'][i];el.id=el.id||el.name;el.maxLength=8000;el.previousElementSibling.setAttribute('for',el.id);});
  const retorno=formConsulta.querySelectorAll('input[type=date]')[1];retorno.name='retorno';retorno.id='retorno';retorno.previousElementSibling.setAttribute('for','retorno');
  document.querySelector('label + #selectCrianca').previousElementSibling.setAttribute('for','selectCrianca');
  document.getElementById('dataConsulta').previousElementSibling.setAttribute('for','dataConsulta');
  document.body.insertAdjacentHTML('beforeend','<dialog id="registroDialog"><div class="dialog-head"><h2>Registro de acompanhamento</h2><button id="fecharRegistro" class="btn btn-cancel">Fechar</button></div><div id="registroDetalhes"></div><button id="imprimirRegistro" class="btn btn-primary">Imprimir registro</button></dialog><div id="print-root"></div>');
})();


